server:
  port: 8888
  contextPath: /

spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/task_service
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

jdbc-datasource:
  test:
    url: jdbc:mysql://localhost:3308/task_service?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: password

hazelcast:
  urls: localhost:5701
